name: Typescript-ASP.NET--EmployeeManagementSystem - Build Provenance Attestation

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  OUT_DIR: '/publish'
  
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Artifact Clean .make*
      uses: zhuxb711/artifacts-size-based-cleanup-action@v1.1.5
      with:
          token: '${{ github.token }}'
          limit: "512MB"
          artifactPaths: '${{ env.OUT_DIR }}/my-app'
          
    - name: Artifact, Checkout
      uses: actions/download-artifact@v4
      with: 
          name: "Employee_Management_System"

    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@v1
      with:
          subject-path: '${{ env.OUT_DIR }}/my-app'
          name: "Employee_Management_System"
