name: Typescript-ASP.NET--EmployeeManagementSystem - Build Attestation

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

env:
  OUT_DIR: '/dist'

permissions:
  contents: read
  
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Artifact, Checkout
      run: ./configure && make ${{ env.OUT_DIR }}/Employee_Management_System
    - name: Attest
      uses: actions/attest-build-provenance@v1
      with:
          subject-path: '${{ github.workspace }}/${{ env.OUT_DIR }}/Employee_Management_System'
