name: Typescript-ASP.NET--EmployeeManagementSystem - Build Provenance Attestation

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  OUT_DIR: 'dist'
  
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    - name: Artifact Clean .make*
      uses: zhuxb711/artifacts-size-based-cleanup-action@v1.1.5
      with:
          token: '${{ github.token }}'
          limit: "512MB"
          artifactPaths: "/home/runner/work/Typescript-ASP.NET--EmployeeManagementSystem/Typescript-ASP.NET--EmployeeManagementSystem/dist/Employee_Management_System"
          
    - name: Artifact, Checkout
      uses: ouzi-dev/go-make-action@v1.5.0
      with: 
          target: '${{ github.workspace }}/${{ env.OUT_DIR }}/Employee_Management_System'
    - name: Attest
      uses: actions/attest-build-provenance@v1.3.3
      with:
          subject-path: '${{ github.workspace }}/${{ env.OUT_DIR }}/Employee_Management_System'
